# Generated by Django 5.2.16 on 2026-09-07 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_newsandevents_summary_es_newsandevents_summary_fr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_registration_open', models.BooleanField(default=True, help_text="When off, students can't add or drop courses themselves.")),
            ],
            options={
                'verbose_name': 'Site configuration',
                'verbose_name_plural': 'Site configuration',
            },
        ),
    ]
