# Generated by Django 5.2.16 on 2026-09-08 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_siteconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsandevents',
            name='event_time',
            field=models.DateTimeField(blank=True, help_text='When the event/news item takes place — shown on the card if set.', null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional image shown on the card.', null=True, upload_to='news_events/'),
        ),
    ]
