# Generated by Django 6.1.1 on 2026-09-21 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_backfill_institution_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='read_aloud_voice_lang',
            field=models.CharField(blank=True, help_text="BCP-47 language tag (e.g. 'en-US') of the preferred read-aloud voice, used as a fallback when a visitor's browser doesn't have the exact voice named above — any voice in this language is used instead of the browser's own default.", max_length=20),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='read_aloud_voice_name',
            field=models.CharField(blank=True, help_text="The exact browser voice name (from the Admin Panel's voice picker) to prefer for the module read-aloud feature. Voices are local to each visitor's browser, so this is only used if that visitor's browser happens to have a voice with this exact name — otherwise read_aloud_voice_lang is used as a fallback.", max_length=150),
        ),
    ]
