# Generated by Django 5.2.16 on 2026-09-08 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_course_length_type_module_courselink_module_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='content',
            field=models.TextField(blank=True, help_text="Optional reading content shown directly on the module's page — e.g. one topic split out of an uploaded document.", null=True),
        ),
    ]
