# Generated by Django 5.2.16 on 2026-09-08 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_module_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='source_document',
            field=models.ForeignKey(blank=True, help_text="The course document this module's content was auto-split from, if any — lets re-opening that document jump back into its modules instead of re-splitting it into duplicates.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_modules', to='course.upload'),
        ),
    ]
