# Generated by Django 5.2.16 on 2026-09-09 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_institution'),
        ('course', '0008_module_source_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='institution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='core.institution'),
        ),
        migrations.AlterField(
            model_name='program',
            name='title',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='program',
            name='title_en',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='title_es',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='title_fr',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='title_ru',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='program',
            unique_together={('institution', 'title'), ('institution', 'title_en'), ('institution', 'title_es'), ('institution', 'title_fr'), ('institution', 'title_ru')},
        ),
    ]
