# Generated by Django 4.0.8 on 2026-09-14 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_backfill_institution_code'),
        ('course', '0010_alter_program_institution_required'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='program',
            unique_together={('institution', 'title')},
        ),
    ]
