# Generated by Django 5.2.16 on 2026-09-07 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_org_admin',
            field=models.BooleanField(default=False, help_text='Organization admin: read/write on facilitators, students, programs & courses, sessions, semesters, exams and course allocations — everything except superuser-only site settings.'),
        ),
    ]
