# Generated by Django 5.2.16 on 2026-09-09 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_is_org_admin'),
        ('core', '0006_institution'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='institution',
            field=models.ForeignKey(blank=True, help_text="Which institution this account belongs to — org admins, facilitators, and students only ever see and manage that institution's data. Left blank for a superuser, who sees across all institutions.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='core.institution'),
        ),
    ]
