upstream dimelms_web {
    server web:8000;
}

server {
    listen 80;
    server_name lms.dimeconsultants.africa 167.71.177.151;

    client_max_body_size 25M;

    # Real client IP/proto will be set by the host-level nginx in front of us.
    set_real_ip_from 172.16.0.0/12;   # docker bridge/default networks
    real_ip_header X-Forwarded-For;

    location /static/ {
        alias /app/staticfiles/;
        expires 30d;
        access_log off;
    }

    location /media/ {
        alias /app/media/;
        expires 7d;
        access_log off;
    }

    location / {
        proxy_pass http://dimelms_web;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $http_x_forwarded_proto;
        proxy_redirect off;
        proxy_read_timeout 120s;
    }
}